---
# defaults file for oc-cluster-up

service_catalog: "true"

hawkular_metrics: "false"

host_config_dir: "{{playbook_dir}}/../ui"

cluster_image: feedhenry/origin

cluster_version: 3.7

cluster_public_hostname: "192.168.37.1"
