apiVersion: v1
kind: Template
metadata:
  name: unified-push-server
  annotations:
    openshift.io/display-name: Unified Push Server
    description: Mobile Push Notification server for sending push notifications to android or iOS
    iconClass: fa fa-upload
    tags: instant-app,push notifications,mobile-service
    template.openshift.io/long-description: Mobile push notification server.
    template.openshift.io/provider-display-name: Aerogear
    template.openshift.io/documentation-url: https://aerogear.org/
    template.openshift.io/support-url: https://github.com/aerogear/aerogear-unifiedpush-server
labels:
  template: unified-push-server
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: unified-push-server
    labels:
      app: unified-push-server
      template: unified-push-server
  spec:
    ports:
    - name: unified-push-server
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      run: unified-push-server
    sessionAffinity: None
    type: ClusterIP