apiVersion: v1
kind: Template
metadata:
  name: remote-debug
  annotations:
    openshift.io/display-name: Remote Debug
    description: Remote debug service for mobile clients. Allowing specific clients to be debugged while users are having issues.
    iconClass: fa fa-life-ring
    tags: instant-app,remote debug,mobile-service
    template.openshift.io/long-description: Remote Debug for mobile clients.
    template.openshift.io/provider-display-name: Feedhenry
    template.openshift.io/documentation-url: https://github.com/feedhenry/remote-debug
    template.openshift.io/support-url: https://github.com/feedhenry/remote-debug/support
labels:
  template: remote-debug
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: remote-debug
    labels:
      app: remote-debug
      template: remote-debug
  spec:
    ports:
    - name: remote-debug
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      run: remote-debug
    sessionAffinity: None
    type: ClusterIP